development:
  cloud_name: dluf3l4ys
  api_key: '973195179265949'
  api_secret: _f-AI3FsOOu3XWezJIA9AQQmgXk
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: dluf3l4ys
  api_key: '973195179265949'
  api_secret: _f-AI3FsOOu3XWezJIA9AQQmgXk
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dluf3l4ys
  api_key: '973195179265949'
  api_secret: _f-AI3FsOOu3XWezJIA9AQQmgXk
  enhance_image_tag: true
  static_image_support: false