default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: vlad
  password: 123
  timeout: 5000

production: 
  adapter: postgresql
  encoding: unicode
  database: store_production
  pool: 5
  username: vlad
  password: 123

development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  username: vlad
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: vlad
  password: 123
